### ISSUE TITLE
Can't log into http://yorick.sourceforge.net/phpBB3/

### ISSUE THREAD

**Issue by jameshume** [dhmunro/yorick#16]
Hi,

Sorry to post this here, I know it's not a Yorick issue, but I cannot for the life of me log into the user forums (I used link off website: http://yorick.sourceforge.net/phpBB3/).

I know the following works
> a = [1,2,3,4,5,6]
> eq_nocopy, b, a
> b(1) = 111
> a(1)
111

All well and good. Should the following work?
> a = [1,2,3,4,5,6]
> eq_nocopy, b, a([1,3,5])
> b(1) = 111
> a(1)
1 /*< oops */

I was hoping that eq_nocopy()ing an array slice would not copy the slice but copy a reference to the slice. Should eq_nocopy be doing this (i.e., am i using it wrong) or is this not what it is for?

Many thanks,
James

**Comment by dhmunro** [comment]
Yes, sorry about the forums.  I can't figure out how to fix it -- if you are a phpBB3 expert, any advice on how to migrate to the sourceforge supported BB would be greatly appreciated.

You cannot do what you want in yorick -- there is no way a yorick array variable can reference a discontiguous hunk of memory.  Yorick treats eq_nocopy like any other function, so it's arguments are evaluated before eq_nocopy is ever called.  Thus, a([1,3,5]) is a temporary array of three elements whose values are copied from a.  The lines::

    eq_nocopy, a, <any yorick expression except a simple variable reference>

**Comment by jameshume** [comment]
Hi David,

Unfortunately I've never used phpBB :-S Thanks for getting back to me though :)
