### ISSUE TITLE
Calling methods of oxy objects embedded inside an oxy object.

### ISSUE THREAD

**Issue by jameshume** [dhmunro/yorick#17]
Hi,

Should it be possible to do something like the following.

func silly(item) { print, item; }
a = save( b = save(c=silly) )
a.b, c, "a silly example"

It generates a syntax error. If I do

d = a.b
d, c, "a silly example"

Yorick is happy. I have tried doing things like the following, but to no avail.

(a.b), c, "a silly example"
noop(a.b), c, "a silly example"

Is there a way in Yorick to do what I'm trying to?

As a second question is there a way to access the context object itself from a function. I know use() can be used to access the members, but what about the object itself so I could, for example, list members and then use them if I don't know the names in advance?

Thank you.

**Comment by dhmunro** [comment]
I agree a.b, c makes more sense, but the yorick oxy objects are at bottom a quick and dirty hack.  To avoid having to modify yorick's parser, I needed to use a comma instead of a period:

    a, b, c, "a silly example"

**Comment by jameshume** [comment]
Okay, that's how you do it... thank you for getting back to me :)
