### ISSUE TITLE
Yorick 2.2.03 command line argument parsing

### ISSUE THREAD

**Issue by jameshume** [dhmunro/yorick#19]
I'm using Yorick 2.2.03 compiled on Ubuntu 12.04.3 LTS. I use the following noddy little test program as a fairly minimal example:

```
print, "GET ARGV"
args = get_argv()
num_args = numberof(args)
print, swrite(format="Got %u arguments", num_args)
print, args

print, "PROCESS ARGV"
args = process_argv()
num_args = numberof(args)
print, swrite(format="Got %u arguments", num_args)
print, args

```

If I call the script using the following command line:

`yorick -batch test.i 1 2 3 "4 5"`

I get the following output:

```
"GET ARGV"
"Got 6 arguments"
["/home/enigma/NewSandboxes/POR3611_TB_Yorick/utils/yorick/bin/yorick","1","2",
"3","4","5"]
"PROCESS ARGV"
"Got 5 arguments"
["1","2","3","4","5"]
```

I was expecting the "4 5" to be grouped as one argument, but it is being presented as two seperate arguments in the returned arrays from `get_argv()` and `process_argv()`. Is Yorick parsing the command line correctly?

**Comment by dhmunro** [comment]
The problem isn't yorick, it's your shell.  I use bash, and I tested it under tcsh.  For me, it works as you expected.  Thus, yorick is faithfully telling you the arguments your shell passed to it.

```
dave@dora:~$ yorick -batch test.i 1 2 3 "4 5"
"GET ARGV"
"Got 5 arguments"
["/usr/lib/yorick/bin/yorick","1","2","3","4 5"]
"PROCESS ARGV"
 Copyright (c) 2005.  The Regents of the University of California.
 All rights reserved.  Yorick 2.2.02 ready.  For help type 'help'
"Got 4 arguments"
["1","2","3","4 5"]
```

**Comment by jameshume** [comment]
Hi,

Thanks for getting back to me. I'm not sure it is... If I compile a simple C program:

```
#include <stdio.h>
int main(int argc, char *argv[]) {
   int idx = 0;
   printf("Got %d arguments\n", argc);
   for(; idx < argc; ++idx) printf("   - %s\n", argv[idx]);
   return 0;
}
```

I get the following output:
$ ./test 1 2 3 "4 5"
Got 5 arguments

```
   - ./test
   - 1
   - 2
   - 3
   - 4 5
```

It works in the same manner if I make a bash script. This suggests to me that the shell is passing in the arguments in the correct manner.

I'll try and debug further...

**Comment by jameshume** [comment]
Sorry to have bothered you! Please ignore this thread, I had an issue with a file that I use as a level of indirection to find the correct Yorick interpreter to run. The error is there and has nothing to do with Yorick!
