### ISSUE TITLE
Yorick 2.2.03 ./configure SIGFPE on Ubuntu running on VirtualBox

### ISSUE THREAD

**Issue by jameshume** [dhmunro/yorick#20]
Hello,

I'm running the `./configure` script for Yorick 2.2.03 build on Ubuntu linux, running on VirtualBox.

The `fputest` utility is giving the following error

```
using FPU_GCC_X86 (SIGFPE delivery)
Floating point exception (core dumped)

*************************WARNING***************************
*** play/unix configuration failed to get SIGFPE delivered
*** read the notes in play/unix/README.fpu
*************************WARNING***************************
```

Just wanted to double check that this is expected behavior? The reason I was wondering is that I can catch SIGFPE using `sigaction()` on my system as opposed to `signal()` as used in `fputest.c`.  

Yorick has otherwise been running fine for quite some time for me so I'm not worries, but wanted to check up on this...

In case the following info helps:

```
$ uname -a
Linux enigma-VirtualBox 3.2.0-53-generic #81-Ubuntu SMP Thu Aug 22 21:03:54 UTC 2013 i686 i686 i386 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.3 LTS
Release:	12.04
Codename:	precise
```

**Comment by dhmunro** [comment]
Yes, it’s expected.  It’s been that way for 10-15 years or so; before that, it worked.  I’ve tracked it into the Linux kernel, but haven’t ever tried to debug the kernel to actually locate the bug.  For some reason it does not happen in yorick itself, only in the fputest program.  I cannot understand why that is, nor do I know whether someday yorick will be linked against some library that wakes up the bug…

SIGFPE delivery is by far the worst problem for numerical programming on modern computers.  I’ve given up on attempting to track it; it’s different in every OS and every programming environment on every platform.

**Comment by jameshume** [comment]
Hi, thanks for letting me know :)
